apiVersion: v1
kind: Service
metadata:
  name: mywebsite
spec:
  type: NodePort
  selector:
    app: mywebsite
  ports:
  - port: 80  
    targetPort: 80
    nodePort: 30007  # Use a specific node port (in the range 30000-32767)
